FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_ORIGIN=http://localhost:5001
ENV NEXT_PUBLIC_API_ORIGIN=$NEXT_PUBLIC_API_ORIGIN

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
