events {
    worker_connections 1024;
}

http {
    client_max_body_size 100M;
    proxy_request_buffering off;
    proxy_read_timeout 300;
    proxy_send_timeout 300;

    upstream frontend {
        server frontend:5002;
    }

    upstream backend {
        server backend:5001;
    }

    # Frontend Server - opms.medicaent.in
    server {
        listen 80;
        server_name opms.medicaent.in;

        location / {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Backend Server - api.medicaent.in
    server {
        listen 80;
        server_name api.medicaent.in;

        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
}
